avoid FrozenStringError from http gem
When consuming this gem in my application, I would sometimes get errors like this:
FrozenError: can't modify frozen String: ""
File /app/vendor/bundle/ruby/2.7.0/gems/http-2.2.2/lib/http/response/body.rb line 57 in force_encoding
File /app/vendor/bundle/ruby/2.7.0/gems/http-2.2.2/lib/http/response/body.rb line 57 in to_s
File /app/vendor/ruby-2.7.4/lib/ruby/2.7.0/forwardable.rb line 235 in to_s

This seems to happen when the response body is empty. Researching the issue leads me to this Github Issue page for the
http gem: https://github.com/httprb/http/issues/640

Which indicates that this is indeed a bug with the 2.2.2 release of the http gem, and there is no fix for it other than
to upgrade to the 4.4.1 release. I have been able to use the brightcove-cmsapi gem with the 4.4.1 version of the http
gem so far without issue.